-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local primary = "rgb(bd93f9)"
local surface = "rgb(282a36)"
local secondary = "rgb(ff79c6)"
local error = "rgb(ff5555)"
local tertiary = "rgb(8be9fd)"
local surface_lowest = "rgb(2d2f3d)"

hl.config({
    general = {
        col = {
            active_border = primary,
            inactive_border = surface,
        },
    },
    group = {
        col = {
            border_active = secondary,
            border_inactive = surface,
            border_locked_active = error,
            border_locked_inactive = surface,
        },
        groupbar = {
            col = {
                active = secondary,
                inactive = surface,
                locked_active = error,
                locked_inactive = surface,
            },
        },
    },
})

