[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]

[GTK]
cursor_theme_name = "Bibata-Modern-Classic"
cursor_blink = true
icon_theme_name = "Papirus-Dark"
theme_name = "Vimix-dark-doder"

[background]
path = "/usr/share/backgrounds/river-city.jpg"
fit = "Fill"

[appearance]
greeting_msg = "Hello There"
