# Appearance
general {
    gaps_in = 2
    gaps_out = 2
    border_size = 2
    col.active_border = rgb(C8507A)
    col.inactive_border = rgb(80485E)
    resize_on_border = true
}

decoration {
    rounding = 3
}

animations {
    enabled = no
}

# VRR
misc {
    vrr = 0
}

# Monitor config
monitor = HDMI-A-2, 1920x1080@120, 0x0, 1
monitor = HDMI-A-1, 1920x1080@120, 1920x0, 1
#Env
env = GTK_THEME,Catppuccin-Dark
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,24

#Exec
exec-once = hyprpaper --c /etc/hyprpaper/hyprpaper.conf
exec-once = regreet && hyprctl dispatch exit
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    disable_hyprland_guiutils_check = true
}

