preload = ~/.local/share/hyprpaper/  # You can still preload a folder

wallpaper {
    monitor = HDMI-A-1                           # Replace with your monitor (e.g., eDP-1, DP-1)
    path = ~/.local/share/hyprpaper/
    timeout = 120                             # Changes every 2 minutes
}

wallpaper {
    monitor = HDMI-A-2                           # Replace with your monitor (e.g., eDP-1, DP-1)
    path = ~/.local/share/hyprpaper/
    timeout = 120                             # Changes every 2 minutes
}
