-- Appearance
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.curve("easeOutCubic", { type = "bezier", points = { { 0.25, 0.46 }, { 0.45, 0.94 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4,
    bezier = "easeOutCubic",
    style = "gnomed",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 4,
    bezier = "easeOutCubic",
    style = "gnomed",
})

hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@120",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@120",
    position = "1920x0",
    scale = "1",
})

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("TERMINAL", "kitty")
hl.env("GTK_CSD", "0")
hl.env("XCURSOR_THEME", "MacOS-Tahoe-Cursor")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "MacOS-Tahoe-Cursor")
hl.env("HYPRCURSOR_SIZE", "24")
local mainMod = "SUPER"
local terminal = "kitty"
local fileManager = "nemo"
local menu = "noctalia msg panel-toggle launcher"
local browser = "google-chrome-stable"
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("hyprshutdown"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser .. " --new-window"))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("hyprpicker -a -n"))
hl.bind(mainMod .. " + X", hl.dsp.window.float({ action = "toggle" }))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("$ipc volume increase"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("$ipc volume decrease"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("$ipc volume muteOutput"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("$ipc brightness increase"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("$ipc brightness decrease"), { locked = true, repeating = true })

hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-2",
    persistent = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-2",
    persistent = true,
})

hl.workspace_rule({
    workspace = "3",
    monitor = "HDMI-A-2",
    persistent = true,
})

hl.workspace_rule({
    workspace = "4",
    monitor = "HDMI-A-2",
    persistent = true,
})

hl.workspace_rule({
    workspace = "5",
    monitor = "HDMI-A-2",
    persistent = true,
})

hl.workspace_rule({
    workspace = "6",
    monitor = "HDMI-A-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "7",
    monitor = "HDMI-A-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "8",
    monitor = "HDMI-A-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "9",
    monitor = "HDMI-A-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "10",
    monitor = "HDMI-A-1",
    persistent = true,
})

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + down", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + right", hl.dsp.window.move({ direction = "r" }))

hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("hyprshot -m output"))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("hyprshot -m window"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume --limit 1.0 @DEFAULT_AUDIO_SINK@ 5%+"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("noctalia msg session-lock"))

-- Source: ~/.config/hypr/noctalia.lua — convert this file to Lua and ensure it is on Lua's package.path.
require("noctalia").apply_theme()
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 3,
        resize_on_border = true,
    },
    decoration = {
        rounding = 20,
        rounding_power = 2,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        blur = {
            enabled = true,
            size = 3,
            passes = 2,
            vibrancy = 0.1696,
        },
    },
    animations = {
        enabled = true,
    },
    -- VRR
    misc = {
        vrr = 2,
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
    -- Monitor config
    --Env
    -- Autostart
    -- Media keys
    -- Pin workspaces to monitors
    -- Workspace switching
    -- Move windows to workspaces
    -- Move windows in tiling layout
    -- Screenshots (hyprshot)
    -- Volume
    -- Lock Screen
    -- HyprEmoji config
    -- For Noctalia Color templates
})

hl.on("hyprland.start", function()
    --hl.exec_cmd("openrgb --profile RGB")
    hl.exec_cmd("noctalia")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    --hl.exec_cmd("uwsm app -- steam")
    --hl.exec_cmd("flatpak run dev.vencord.Vesktop")
end)

